-- Table 1: USER
CREATE TABLE IF NOT EXISTS USER (
    username VARCHAR(50) PRIMARY KEY, 
    salt VARCHAR(50) NOT NULL,
    passwordHash VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    role VARCHAR(10) NOT NULL
);

-- Table 2: AGENT
CREATE TABLE IF NOT EXISTS AGENT (
    id VARCHAR(10) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    role VARCHAR(10) NOT NULL
);

-- Table 3: COMPLAINT
CREATE TABLE IF NOT EXISTS COMPLAINT (
    id VARCHAR(20) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    reporter VARCHAR(50),
    assignedTo VARCHAR(100),
    category VARCHAR(50) NOT NULL,
    priority VARCHAR(10) NOT NULL,
    status VARCHAR(20) NOT NULL,
    createdAt VARCHAR(30) NOT NULL,
    resolvedAt VARCHAR(30),
    details TEXT,
    
    FOREIGN KEY (reporter) REFERENCES USER(username)
);

-- Table 4: FEEDBACK
CREATE TABLE IF NOT EXISTS FEEDBACK (
    id VARCHAR(20) PRIMARY KEY,
    complaintId VARCHAR(20) NOT NULL,
    author VARCHAR(50),
    date VARCHAR(30) NOT NULL,
    comment VARCHAR(500),
    rating INT NOT NULL,
    
    FOREIGN KEY (complaintId) REFERENCES COMPLAINT(id)
);

-- Table 5: HISTORY
CREATE TABLE IF NOT EXISTS HISTORY (
    entry_id INT AUTO_INCREMENT PRIMARY KEY,
    complaintId VARCHAR(20) NOT NULL,
    time VARCHAR(30) NOT NULL,
    action VARCHAR(50) NOT NULL,
    actor VARCHAR(50) NOT NULL,
    note VARCHAR(255),
    
    FOREIGN KEY (complaintId) REFERENCES COMPLAINT(id)
);

-- Table 6: ATTACHMENT
CREATE TABLE IF NOT EXISTS ATTACHMENT (
    attach_id INT AUTO_INCREMENT PRIMARY KEY,
    complaintId VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    data LONGBLOB NOT NULL,
    
    FOREIGN KEY (complaintId) REFERENCES COMPLAINT(id)
);

-- Table 7: CATEGORY_LOOKUP
CREATE TABLE IF NOT EXISTS CATEGORY_LOOKUP (
    name VARCHAR(50) PRIMARY KEY
);

-- Table 8: PRIORITY_LOOKUP
CREATE TABLE IF NOT EXISTS PRIORITY_LOOKUP (
    name VARCHAR(10) PRIMARY KEY
);
